'use strict';
(() => {
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const ui=Object.fromEntries(['count','level','distance','progress','overlay','eyebrow','heading','description','rules','start','hint','pause','toast','battle','dragHint','status','left','right'].map(id=>[id,document.getElementById(id)]));
const VIEW=110, PLAYER_Z=7, END=310;
let W=480,H=600,dpr=1,mode='ready',previousMode='run',level=1,units=10,playerX=0,targetX=0,distance=0,time=0,last=0,objects=[],particles=[],shots=[],battle=null,keys={},drag=null,toastUntil=0,fireClock=0,enemyClock=0,winDelay=0;
function resize(){const b=canvas.getBoundingClientRect();W=b.width;H=b.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}
new ResizeObserver(resize).observe(canvas);
function plan(){objects=[];const plus=(z,left,right)=>objects.push({kind:'gates',z,choices:[left,right],used:false});const orb=(z,x)=>objects.push({kind:'orb',z,x,used:false});const block=(z,x)=>objects.push({kind:'block',z,x,used:false});const enemy=(z,n)=>objects.push({kind:'enemy',z,n,used:false});
plus(29,{op:'+',n:6},{op:'+',n:10});for(let i=0;i<5;i++)orb(41+i*3,-.64);
plus(64,{op:'×',n:2},{op:'+',n:8});enemy(82,22+level*5);
plus(111,{op:'+',n:12},{op:'+',n:20});block(131,.55);for(let i=0;i<6;i++)orb(134+i*3,-.58);
plus(162,{op:'+',n:15},{op:'×',n:2});enemy(184,48+level*12);
plus(214,{op:'×',n:2},{op:'+',n:25});for(let i=0;i<5;i++)orb(232+i*3,.58);block(245,-.55);
plus(266,{op:'+',n:15},{op:'+',n:30});enemy(292,100+level*20);}
function updateHUD(){ui.count.textContent=units;ui.level.textContent=`第 ${level} 关`;const p=Math.min(100,Math.round(distance/END*100));ui.distance.textContent=`${p} / 100%`;ui.progress.style.width=p+'%';}
function toast(text,color='#fff'){ui.toast.textContent=text;ui.toast.style.color=color;ui.toast.classList.add('show');toastUntil=time+1.35;}
function start(){if(mode==='paused'){mode=previousMode;ui.overlay.hidden=true;ui.pause.textContent='Ⅱ';ui.pause.setAttribute('aria-label','暂停游戏');return;}if(mode==='won')level++;units=10;playerX=targetX=0;distance=0;shots=[];particles=[];battle=null;fireClock=enemyClock=winDelay=0;keys={};plan();mode='run';ui.overlay.hidden=true;ui.pause.disabled=false;ui.pause.textContent='Ⅱ';ui.battle.hidden=true;ui.status.textContent='收集队员，选择人数更多的蓝门';ui.dragHint.classList.add('visible');updateHUD();}
function pause(){if(mode==='paused'){start();return;}if(!['run','fight'].includes(mode))return;previousMode=mode;mode='paused';keys={};drag=null;ui.overlay.hidden=false;ui.eyebrow.textContent='TAKE A BREAK';ui.heading.textContent='休息一下';ui.description.textContent='准备好后，继续带领蓝队闯关。';ui.rules.hidden=true;ui.start.innerHTML='继续游戏 <span aria-hidden="true">▶</span>';ui.hint.textContent='当前进度已保留';ui.pause.textContent='▶';ui.pause.setAttribute('aria-label','继续游戏');}
function finish(won){mode=won?'won':'lost';ui.pause.disabled=true;ui.battle.hidden=true;ui.overlay.hidden=false;ui.rules.hidden=true;ui.eyebrow.textContent=won?'BRIDGE CLEARED':'TRY AGAIN';ui.heading.textContent=won?'蓝队，胜利！':'再集结一次';ui.description.textContent=won?`你带领 ${units} 位队员冲过了长桥。`:'多收集金球和队员，选择 ×2 的蓝门再试一次。';ui.start.textContent=won?'挑战下一关':'再试一次';ui.hint.textContent=won?`第 ${level} 关完成`:'左右拖动，提前选择路线';ui.status.textContent=won?'长桥已通关':'重新集结，继续挑战';}
ui.start.addEventListener('click',start);ui.pause.addEventListener('click',pause);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
window.addEventListener('blur',()=>{keys={};if(mode==='run'||mode==='fight')pause();});
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','d','A','D',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'||e.key===' '){if(e.repeat)return;if(mode==='ready'||mode==='won'||mode==='lost')start();else pause();}keys[e.key.toLowerCase()]=true;});
window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointerdown',e=>{if(!['run','fight'].includes(mode))return;canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,start:targetX};ui.dragHint.classList.remove('visible');});
canvas.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId)targetX=clamp(drag.start+(e.clientX-drag.x)/(W*.38),-.76,.76);});
const release=()=>{drag=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
for(const [button,key] of [[ui.left,'arrowleft'],[ui.right,'arrowright']]){button.addEventListener('pointerdown',e=>{button.setPointerCapture(e.pointerId);keys[key]=true;ui.dragHint.classList.remove('visible');});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keys[key]=false);}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function point(x,z){const t=clamp(1-z/VIEW,0,1),f=t*t;return{x:W/2+x*W*(.07+.405*f),y:H*.095+H*.84*f,s:.13+.99*f};}
function text(str,x,y,size,color='#fff',outline=true){ctx.font=`900 ${size}px system-ui,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';if(outline){ctx.lineWidth=Math.max(2,size*.12);ctx.strokeStyle='#082237a0';ctx.strokeText(str,x,y);}ctx.fillStyle=color;ctx.fillText(str,x,y);}
function polygon(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function circle(x,y,r,color){ctx.beginPath();ctx.arc(x,y,Math.max(.1,r),0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function burst(x,z,color,n=12){for(let i=0;i<n;i++)particles.push({x,z,dx:(Math.random()-.5)*.65,dz:(Math.random()-.5)*10,life:.6,max:.6,color});}
function soldier(x,z,color,index=0,scale=1){const p=point(x,z),s=p.s*scale,r=6.4*s,bob=Math.sin(time*9+index)*1.2*s;ctx.fillStyle='#00324840';ctx.beginPath();ctx.ellipse(p.x+5*s,p.y+4*s,r*1.3,r*.5,0,0,7);ctx.fill();ctx.strokeStyle=color==='blue'?'#064a9a':'#8e1d35';ctx.lineWidth=3.5*s;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p.x-2*s,p.y-4*s);ctx.lineTo(p.x-4*s,p.y+2*s+bob);ctx.moveTo(p.x+2*s,p.y-4*s);ctx.lineTo(p.x+4*s,p.y+2*s-bob);ctx.stroke();circle(p.x,p.y-10*s,r,color==='blue'?'#1b9deb':'#ef4a65');ctx.strokeStyle=color==='blue'?'#5bd8ff':'#ff8d94';ctx.lineWidth=2*s;ctx.beginPath();ctx.moveTo(p.x-6*s,p.y-10*s);ctx.lineTo(p.x-9*s,p.y-3*s);ctx.stroke();circle(p.x,p.y-19*s,r*.85,color==='blue'?'#64c8fa':'#fa7286');ctx.fillStyle=color==='blue'?'#0966bd':'#bf2847';ctx.fillRect(p.x-r*.9,p.y-21*s,r*1.8,3*s);ctx.strokeStyle='#15314c';ctx.lineWidth=2.5*s;ctx.beginPath();ctx.moveTo(p.x+6*s,p.y-7*s);ctx.lineTo(p.x+6*s,p.y-19*s);ctx.stroke();}
function squad(x,z,n,color){const display=Math.min(n,84),cols=Math.max(1,Math.ceil(Math.sqrt(display*1.2))),rows=Math.ceil(display/cols);for(let row=rows-1;row>=0;row--)for(let col=0;col<cols;col++){const i=row*cols+col;if(i>=display)continue;soldier(x+(col-(cols-1)/2)*.055,z+row*1.25,color,i);}const p=point(x,z+rows*1.25);const width=Math.max(44,40*p.s),height=25*Math.max(.6,p.s);ctx.fillStyle=color==='blue'?'#087fe5':'#da2544';ctx.fillRect(p.x-width/2,p.y-height-23*p.s,width,height);text(String(n),p.x,p.y-height/2-23*p.s,Math.max(15,21*p.s));}
function gate(o){const z=o.z-distance;for(let side=0;side<2;side++){const x=side===0?-.49:.49,choice=o.choices[side],p=point(x,z),a=point(x-.38,z),b=point(x+.38,z),height=48*p.s;ctx.strokeStyle='#11628c';ctx.lineWidth=5*p.s;ctx.beginPath();ctx.moveTo(a.x,p.y);ctx.lineTo(a.x,p.y-height-25*p.s);ctx.moveTo(b.x,p.y);ctx.lineTo(b.x,p.y-height-25*p.s);ctx.stroke();const grd=ctx.createLinearGradient(0,p.y-height,0,p.y);grd.addColorStop(0,'#5bd2ffdc');grd.addColorStop(1,'#087bd955');ctx.fillStyle=grd;ctx.fillRect(a.x,p.y-height,b.x-a.x,height);ctx.fillStyle='#087fe5';ctx.fillRect(a.x-2*p.s,p.y-height-26*p.s,b.x-a.x+4*p.s,30*p.s);text(choice.op+choice.n,p.x,p.y-height-11*p.s,Math.max(15,25*p.s));}}
function drawObject(o){const z=o.z-distance;if(o.used||z<-7||z>VIEW)return;if(o.kind==='gates'){gate(o);return;}const p=point(o.x||0,z);if(o.kind==='orb'){ctx.fillStyle='#3e45044d';ctx.beginPath();ctx.ellipse(p.x+4*p.s,p.y+3*p.s,10*p.s,4*p.s,0,0,7);ctx.fill();const g=ctx.createRadialGradient(p.x-4*p.s,p.y-15*p.s,1,p.x,p.y-10*p.s,12*p.s);g.addColorStop(0,'#fffccc');g.addColorStop(.4,'#ffe865');g.addColorStop(1,'#ce980a');circle(p.x,p.y-10*p.s,12*p.s,g);}else if(o.kind==='block'){const w=23*p.s,h=28*p.s;ctx.fillStyle='#db681c';ctx.fillRect(p.x-w,p.y-h,w*2,h);polygon([{x:p.x-w,y:p.y-h},{x:p.x-w+9*p.s,y:p.y-h-7*p.s},{x:p.x+w+9*p.s,y:p.y-h-7*p.s},{x:p.x+w,y:p.y-h}],'#ffad32');ctx.save();ctx.beginPath();ctx.rect(p.x-w,p.y-h,w*2,h);ctx.clip();ctx.strokeStyle='#ffde76';ctx.lineWidth=8*p.s;for(let i=-2;i<4;i++){ctx.beginPath();ctx.moveTo(p.x-w+i*20*p.s,p.y);ctx.lineTo(p.x-w+i*20*p.s+20*p.s,p.y-h);ctx.stroke();}ctx.restore();}else if(o.kind==='enemy'){squad(0,z,o.n,'red');}}
function draw(){ctx.clearRect(0,0,W,H);const sea=ctx.createLinearGradient(0,0,0,H);sea.addColorStop(0,'#72cfe5');sea.addColorStop(.15,'#178faf');sea.addColorStop(1,'#075da0');ctx.fillStyle=sea;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#74dfff35';ctx.lineWidth=2;for(let i=0;i<35;i++){const y=H*.16+i/35*H*.87,w=12+i*1.8;for(let j=0;j<5;j++){const x=(j*W*.26+Math.sin(i*3+j)*30+time*(5+i/4))%(W+80)-40;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+w/2,y+3,x+w,y);ctx.stroke();}}
const farL=point(-1,VIEW),farR=point(1,VIEW),nearL=point(-1,-1),nearR=point(1,-1);polygon([farL,farR,nearR,nearL],'#9eabb4');polygon([point(-.99,VIEW),point(-.96,VIEW),point(-.96,0),point(-.99,0)],'#d6e4e9');polygon([point(.96,VIEW),point(.99,VIEW),point(.99,0),point(.96,0)],'#d6e4e9');
for(let z=VIEW;z>-10;z-=6){const dz=z-(distance%6);for(const x of [-1.02,1.02]){const p=point(x,dz);ctx.strokeStyle='#24445c';ctx.lineWidth=2*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y-13*p.s);ctx.stroke();}}for(const x of [-1.02,1.02]){const a=point(x,VIEW),b=point(x,0);ctx.strokeStyle='#284963';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,a.y-13*a.s);ctx.lineTo(b.x,b.y-13*b.s);ctx.stroke();}
for(let z=0;z<VIEW;z+=13){const dz=z-distance%13;if(dz<0)continue;for(const x of [-.33,.33]){const a=point(x,dz),b=point(x,dz+4);ctx.strokeStyle='#e9edf0aa';ctx.lineWidth=3*a.s;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}
objects.filter(o=>!o.used&&o.z-distance<VIEW).sort((a,b)=>b.z-a.z).forEach(drawObject);
if(battle){squad(0,39,Math.max(0,Math.ceil(battle.hp)),'red');const p=point(0,52);const width=W*.34;ctx.fillStyle='#671d31';ctx.fillRect(p.x-width/2,p.y-34,width,5);ctx.fillStyle='#ff607a';ctx.fillRect(p.x-width/2,p.y-34,width*Math.max(0,battle.hp/battle.max),5);}
squad(playerX,PLAYER_Z,units,'blue');for(const s of shots){const p=point(s.x,s.z);ctx.fillStyle=s.enemy?'#ffb4a6':'#fffec4';ctx.shadowBlur=6;ctx.shadowColor=ctx.fillStyle;ctx.fillRect(p.x-2*p.s,p.y-16*p.s,4*p.s,10*p.s);ctx.shadowBlur=0;}
for(const f of particles){const p=point(f.x,f.z);ctx.globalAlpha=f.life/f.max;circle(p.x,p.y-15*p.s,4*p.s,f.color);}ctx.globalAlpha=1;
if(mode==='ready'){text('+1',point(.65,32).x,point(.65,32).y-30,28,'#daf8ff');}
}
function update(dt){time+=dt;if(time>toastUntil)ui.toast.classList.remove('show');if(!['run','fight'].includes(mode))return;
if(keys.arrowleft||keys.a)targetX-=dt*1.55;if(keys.arrowright||keys.d)targetX+=dt*1.55;targetX=clamp(targetX,-.76,.76);playerX+=(targetX-playerX)*Math.min(1,dt*15);
if(mode==='run'){distance+=dt*(11+Math.min(level,8)*.6);if(distance>12)ui.dragHint.classList.remove('visible');for(const o of objects){if(o.used)continue;const z=o.z-distance;if(o.kind==='enemy'&&z<=40){o.used=true;battle={hp:o.n,max:o.n};mode='fight';ui.battle.hidden=false;ui.status.textContent='自动攻击中 · 保持集结';toast('红队来袭！','#ffb5be');break;}if(z>PLAYER_Z)continue;o.used=true;if(o.kind==='gates'){const c=o.choices[playerX<0?0:1],old=units;units=Math.min(300,c.op==='×'?units*c.n:units+c.n);toast(`+${units-old} 位队员`,'#a1e7ff');burst(playerX,PLAYER_Z,'#6fdcff',16);}else if(o.kind==='orb'&&Math.abs(playerX-o.x)<.28){units=Math.min(300,units+3);toast('+3 位队员','#ffdf68');burst(o.x,PLAYER_Z,'#ffe664',7);}else if(o.kind==='block'&&Math.abs(playerX-o.x)<.29){units=Math.max(0,units-8);toast('路障！损失 8 人','#ffc09a');burst(o.x,PLAYER_Z,'#ff9948');if(units<=0){finish(false);break;}}}if(distance>=END)finish(true);
}else if(mode==='fight'){fireClock+=dt;enemyClock+=dt;if(fireClock>.12){fireClock=0;const power=Math.max(.7,units*.029);battle.hp-=power;for(let i=0;i<Math.min(5,Math.ceil(units/15));i++)shots.push({x:playerX+(Math.random()-.5)*.2,z:PLAYER_Z+4,enemy:false});burst(0,39,'#ff8191',2);}if(enemyClock>.72&&battle.hp>0){enemyClock=0;units=Math.max(0,units-Math.max(1,Math.ceil(battle.max*.013)));shots.push({x:playerX,z:37,enemy:true});if(units===0)finish(false);}if(battle.hp<=0){winDelay+=dt;if(winDelay>.3){battle=null;winDelay=0;mode='run';ui.battle.hidden=true;toast('击退红队！','#acecff');ui.status.textContent='继续前进，集结更多队员';burst(0,39,'#ffe779',25);}}}
for(const s of shots)s.z+=dt*(s.enemy?-65:85);shots=shots.filter(s=>s.z>3&&s.z<42);for(const f of particles){f.life-=dt;f.x+=f.dx*dt;f.z+=f.dz*dt;}particles=particles.filter(f=>f.life>0);updateHUD();}
function frame(stamp){const dt=Math.min(.035,(stamp-last)/1000||.016);last=stamp;update(dt);draw();requestAnimationFrame(frame);}
plan();resize();requestAnimationFrame(frame);
})();
